// scripts/build-catalog.mjs
// Comprehensive audit, correction, and enrichment of GTMShelf tool catalog (70 tools)
import fs from 'fs';
import path from 'path';

const AUDITED_TOOLS = [
  // --- STAGE 1: ATTRACT ---
  {
    id: 'copy-ai',
    slug: 'copy-ai',
    name: 'Copy.ai',
    domain: 'copy.ai',
    stage: 1,
    cat: 'GTM AI workflows',
    tagline: 'GTM workflow automation platform combining prospect research with outreach copy',
    description: 'Copy.ai automates repetitive go-to-market workflows, enriching target accounts, drafting tailored cold emails in bulk, and synchronizing intelligence to CRMs.',
    price: 'Free plan',
    price_note: 'Free tier available (2,000 words); Starter from $36/mo (billed annually, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: true,
    best: 'Revenue teams seeking automated account research and bulk copy generation in one workspace',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Bulk GTM research and personalized email drafting workflows',
    secondary_capabilities: ['Marketing copywriting', 'CRM data push', 'Workflow templates'],
    buyer_segment: 'Growth teams & RevOps',
    gtm_buckets: ['Inbound', 'Outbound', 'Data & Orchestration'],
    overlapping_tools: ['jasper', 'regie-ai'],
    min_plan: 'Free tier / Starter ($36/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'surfer',
    slug: 'surfer',
    name: 'Surfer',
    domain: 'surferseo.com',
    stage: 1,
    cat: 'SEO',
    tagline: 'Content intelligence and on-page SERP optimization engine',
    description: 'Surfer analyzes top search engine results to provide actionable content guidelines, keyword density recommendations, and internal linking suggestions.',
    price: 'Paid',
    price_note: 'Essential from $89/mo (checked October 2026)',
    ints: ['Google Workspace', 'WordPress'],
    feat: false,
    best: 'Content marketers and SEO specialists aiming for higher organic search rankings',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'SERP analysis and real-time on-page content optimization',
    secondary_capabilities: ['Keyword research', 'Content audit', 'SERP analyzer'],
    buyer_segment: 'Marketing teams & SEO agencies',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['clearscope', 'marketmuse'],
    min_plan: 'Essential ($89/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'clearscope',
    slug: 'clearscope',
    name: 'Clearscope',
    domain: 'clearscope.io',
    stage: 1,
    cat: 'SEO',
    tagline: 'Enterprise content optimization and SEO grading platform',
    description: 'Clearscope uses search intent analysis to guide content creators on relevant topics, search terms, and readability standards that perform on Google.',
    price: 'Paid',
    price_note: 'Essentials from $189/mo (checked October 2026)',
    ints: ['Google Workspace', 'WordPress'],
    feat: false,
    best: 'Enterprise editorial teams requiring high-precision keyword modeling and content grading',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Enterprise keyword modeling and real-time content grading',
    secondary_capabilities: ['Content inventory', 'Search intent tracking'],
    buyer_segment: 'Mid-market & Enterprise editorial teams',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['surfer', 'marketmuse'],
    min_plan: 'Essentials ($189/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'semrush',
    slug: 'semrush',
    name: 'Semrush',
    domain: 'semrush.com',
    stage: 1,
    cat: 'SEO',
    tagline: 'All-in-one search marketing, competitor analysis, and keyword intelligence suite',
    description: 'Semrush offers comprehensive tools for keyword research, competitive domain benchmarking, backlink audits, and technical SEO monitoring.',
    price: 'Paid',
    price_note: 'Pro from $139.95/mo ($117.33/mo billed annually, checked October 2026)',
    ints: ['Google Workspace', 'Zapier'],
    feat: true,
    best: 'Full-service marketing teams managing organic search, paid search, and competitor surveillance',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Comprehensive keyword research and competitor domain benchmarking',
    secondary_capabilities: ['Backlink tracking', 'Site audit', 'PPC keyword intelligence'],
    buyer_segment: 'Marketing teams of all sizes',
    gtm_buckets: ['Inbound'],
    overlapping_tools: [],
    min_plan: 'Pro ($139.95/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'marketmuse',
    slug: 'marketmuse',
    name: 'MarketMuse',
    domain: 'marketmuse.com',
    stage: 1,
    cat: 'SEO',
    tagline: 'AI content strategy platform and semantic topic modeling',
    description: 'MarketMuse analyzes entire content domains to uncover topic gaps, cluster opportunities, and strategic content plans based on competitive authority.',
    price: 'Free plan',
    price_note: 'Free tier (10 queries/mo); Standard from $149/mo (checked October 2026)',
    ints: ['Google Workspace'],
    feat: false,
    best: 'Content strategists building topic clusters and competitive authority',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Content clustering and authority gap analysis',
    secondary_capabilities: ['Content briefs', 'Semantic topic modeling'],
    buyer_segment: 'Mid-market content strategy teams',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['surfer', 'clearscope'],
    min_plan: 'Free tier / Standard ($149/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'adcreative-ai',
    slug: 'adcreative-ai',
    name: 'AdCreative.ai',
    domain: 'adcreative.ai',
    stage: 1,
    cat: 'Ad creative',
    tagline: 'Generates ad visuals and copy variants optimized for performance',
    description: 'AdCreative.ai produces branded ad banners, social posts, and ad copy variants formatted for Meta, Google, and LinkedIn ad platforms.',
    price: 'Paid',
    price_note: 'Starter from $29/mo (checked October 2026)',
    ints: ['Zapier'],
    feat: false,
    best: 'Growth marketers running multi-variant digital advertising campaigns',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'High-velocity banner generation and advertising creative variants',
    secondary_capabilities: ['Ad copy generation', 'Scoring predictor'],
    buyer_segment: 'Performance marketing agencies & D2C/B2B brands',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['madgicx', 'canva'],
    min_plan: 'Starter ($29/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'madgicx',
    slug: 'madgicx',
    name: 'Madgicx',
    domain: 'madgicx.com',
    stage: 1,
    cat: 'Ad creative',
    tagline: 'AI omnichannel ad management and creative analytics platform',
    description: 'Madgicx provides automated ad bidding, creative performance dashboards, audience discovery, and budget optimization for Meta and Google Ads.',
    price: 'Paid',
    price_note: 'Starts at $29 to $55/mo based on ad spend (checked October 2026)',
    ints: ['Zapier'],
    feat: false,
    best: 'E-commerce and B2B paid media managers seeking automated budget and audience rules',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Automated paid advertising optimization and creative insights',
    secondary_capabilities: ['Audience targeting', 'Bid automation'],
    buyer_segment: 'Paid media managers & performance agencies',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['adcreative-ai'],
    min_plan: 'All-in-One ($29/mo+ based on ad spend)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'canva',
    slug: 'canva',
    name: 'Canva',
    domain: 'canva.com',
    stage: 1,
    cat: 'Ad creative',
    tagline: 'Visual communication and collaborative design platform',
    description: 'Canva empowers marketing and sales teams to create presentations, social graphics, documents, and promotional assets without specialized design training.',
    price: 'Free plan',
    price_note: 'Free tier available; Pro from $15/mo or $120/yr (checked October 2026)',
    ints: ['Slack', 'Google Workspace'],
    feat: true,
    best: 'GTM teams needing rapid visual asset creation and brand consistency',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Self-serve visual design and team marketing asset creation',
    secondary_capabilities: ['Presentation templates', 'Social post resizing', 'Brand kits'],
    buyer_segment: 'All business sizes',
    gtm_buckets: ['Inbound'],
    overlapping_tools: [],
    min_plan: 'Free tier / Pro ($15/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'buffer',
    slug: 'buffer',
    name: 'Buffer',
    domain: 'buffer.com',
    stage: 1,
    cat: 'Social media',
    tagline: 'Social media publishing, scheduling, and analytics platform',
    description: 'Buffer streamlines multi-channel social posting across LinkedIn, X/Twitter, Instagram, and Mastodon with intuitive queueing and performance insights.',
    price: 'Free plan',
    price_note: 'Free tier (up to 3 channels); Essentials from $6/channel/mo (checked October 2026)',
    ints: ['Zapier'],
    feat: false,
    best: 'Founders and lean marketing teams maintaining a consistent social presence',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Social media queue scheduling and post publishing',
    secondary_capabilities: ['Engagement dashboard', 'Link in bio tool'],
    buyer_segment: 'Solopreneurs, startups, and boutique agencies',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['hootsuite'],
    min_plan: 'Free tier / Essentials ($6/channel/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'jasper',
    slug: 'jasper',
    name: 'Jasper',
    domain: 'jasper.ai',
    stage: 1,
    cat: 'Content writing',
    tagline: 'AI marketing copilot for enterprise brand voice and content campaigns',
    description: 'Jasper assists marketing departments in drafting blogs, emails, and campaign briefs aligned with defined company voice and style guidelines.',
    price: 'Paid',
    price_note: 'Creator from $39/mo ($49/mo billed monthly, checked October 2026)',
    ints: ['Google Workspace', 'Zapier'],
    feat: false,
    best: 'Content teams looking to maintain brand voice guidelines across multi-channel campaigns',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Brand-governed marketing copy generation',
    secondary_capabilities: ['Campaign asset drafting', 'Company knowledge hub'],
    buyer_segment: 'Marketing departments & creative agencies',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['copy-ai', 'writesonic'],
    min_plan: 'Creator ($39/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'writesonic',
    slug: 'writesonic',
    name: 'Writesonic',
    domain: 'writesonic.com',
    stage: 1,
    cat: 'Content writing',
    tagline: 'AI writing tool and SEO-focused article generator',
    description: 'Writesonic provides article generation, ad copy templates, and Chatsonic conversational assistance powered by web search data.',
    price: 'Free plan',
    price_note: 'Free tier (25 credits); Individual from $16/mo ($20/mo monthly, checked October 2026)',
    ints: ['Zapier', 'WordPress'],
    feat: false,
    best: 'Content writers and small agencies generating long-form drafts and marketing blurbs',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Long-form blog post drafting and marketing copy creation',
    secondary_capabilities: ['Chatbot creation', 'SEO keyword integration'],
    buyer_segment: 'Freelancers & small business marketing teams',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['jasper', 'copy-ai'],
    min_plan: 'Free tier / Individual ($16/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'hootsuite',
    slug: 'hootsuite',
    name: 'Hootsuite',
    domain: 'hootsuite.com',
    stage: 1,
    cat: 'Social media',
    tagline: 'Enterprise social media management, listening, and compliance suite',
    description: 'Hootsuite enables large marketing teams to plan social calendars, monitor brand sentiment, delegate customer service tickets, and measure ROI across networks.',
    price: 'Paid',
    price_note: 'Professional from $99/mo (1 user, 10 accounts, checked October 2026)',
    ints: ['Salesforce', 'Slack', 'HubSpot'],
    feat: false,
    best: 'Mid-market and enterprise brands with dedicated social media and PR teams',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Enterprise multi-account social scheduling, listening, and team governance',
    secondary_capabilities: ['Social listening', 'Team approval workflows', 'Benchmarking'],
    buyer_segment: 'Mid-market & Enterprise marketing organizations',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['buffer'],
    min_plan: 'Professional ($99/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'gamma',
    slug: 'gamma',
    name: 'Gamma',
    domain: 'gamma.app',
    stage: 1,
    cat: 'Content writing',
    tagline: 'AI-powered presentation, document, and webpage generator',
    description: 'Gamma turns prompts or outlines into formatted decks, docs, and interactive web pages with responsive card layouts and embedded media.',
    price: 'Free plan',
    price_note: 'Free tier (400 credits); Plus from $8/user/mo ($10/mo monthly, checked October 2026)',
    ints: ['Google Workspace'],
    feat: false,
    best: 'Sales reps and founders producing interactive pitch decks and visual collateral quickly',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Rapid AI generation of presentation slides and client collateral',
    secondary_capabilities: ['Interactive card layouts', 'Document embedding'],
    buyer_segment: 'Founders, sales reps, and agency consultants',
    gtm_buckets: ['Inbound', 'Outbound'],
    overlapping_tools: ['beautiful-ai'],
    min_plan: 'Free tier / Plus ($8/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'descript',
    slug: 'descript',
    name: 'Descript',
    domain: 'descript.com',
    stage: 1,
    cat: 'Content writing',
    tagline: 'Text-based audio and video editing platform for marketing teams',
    description: 'Descript enables creators to edit video and podcast recordings like a text document, with automated transcription, filler word removal, and AI voice cloning.',
    price: 'Free plan',
    price_note: 'Free tier (1 hr/mo); Hobbyist from $12/user/mo ($19/mo monthly, checked October 2026)',
    ints: ['Slack', 'Zapier'],
    feat: false,
    best: 'GTM teams producing customer interview snippets, product clips, and podcast episodes',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Transcript-based video and podcast editing for marketing distribution',
    secondary_capabilities: ['Studio sound enhancement', 'Screen recording', 'AI green screen'],
    buyer_segment: 'Content creators and marketing teams',
    gtm_buckets: ['Inbound'],
    overlapping_tools: [],
    min_plan: 'Free tier / Hobbyist ($12/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'beautiful-ai',
    slug: 'beautiful-ai',
    name: 'Beautiful.ai',
    domain: 'beautiful.ai',
    stage: 1,
    cat: 'Content writing',
    tagline: 'Smart presentation software with automated slide design rules',
    description: 'Beautiful.ai uses intelligent design constraints to automatically format slide typography, margins, and data charts into professional pitch decks.',
    price: 'Paid',
    price_note: 'Pro from $12/mo (billed annually as $144/yr, checked October 2026)',
    ints: ['Slack', 'Google Workspace'],
    feat: false,
    best: 'Enterprise sales and executive teams building on-brand pitch and QBR presentations',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Automated executive pitch deck formatting and slide aesthetics',
    secondary_capabilities: ['Team slide templates', 'Real-time chart styling'],
    buyer_segment: 'Consultancies, sales leadership, and founders',
    gtm_buckets: ['Inbound'],
    overlapping_tools: ['gamma'],
    min_plan: 'Pro ($12/mo billed annually)',
    pricing_verified_at: 'October 2026',
  },

  // --- STAGE 2: PROSPECT ---
  {
    id: 'clay',
    slug: 'clay',
    name: 'Clay',
    domain: 'clay.com',
    stage: 2,
    cat: 'Lead data',
    tagline: 'Waterfall data enrichment and automated outbound prospecting engine',
    description: 'Clay chains together 50+ data providers to verify emails, find mobile numbers, synthesize company insights via AI, and feed personalized lists into outreach engines.',
    price: 'Free plan',
    price_note: 'Free tier (100 credits); Starter from $149/mo (2,000 credits, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: true,
    best: 'Growth engineers and modern outbound teams wanting maximum contact coverage without multiple standalone subscriptions',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Multi-vendor waterfall enrichment and AI research prompt automation',
    secondary_capabilities: ['Web scraping', 'Formula enrichment', 'CRM write-back'],
    buyer_segment: 'Modern outbound teams & growth architects',
    gtm_buckets: ['Outbound', 'Data & Orchestration'],
    overlapping_tools: ['apollo', 'zoominfo'],
    min_plan: 'Free tier / Starter ($149/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'apollo',
    slug: 'apollo',
    name: 'Apollo',
    domain: 'apollo.io',
    stage: 2,
    cat: 'Lead data',
    tagline: 'Comprehensive B2B contact database with native sales engagement and dialer',
    description: 'Apollo provides access to 275M+ verified buyer profiles, direct phone numbers, email search, sequence automation, and inbound conversation intelligence.',
    price: 'Free plan',
    price_note: 'Free tier (limited credits); Basic from $49/seat/mo ($59 monthly, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Zapier'],
    feat: true,
    best: 'Early-stage to mid-market sales teams seeking an all-in-one prospecting and sequencing engine',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'B2B contact search, verified email/phone lookups, and basic outbound sequences',
    secondary_capabilities: ['Chrome extension', 'Built-in dialer', 'Buying intent filters'],
    buyer_segment: 'Startups, sales reps, and mid-market teams',
    gtm_buckets: ['Outbound', 'Lead Capture'],
    overlapping_tools: ['zoominfo', 'lusha', 'instantly', 'smartlead'],
    min_plan: 'Free tier / Basic ($49/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'zoominfo',
    slug: 'zoominfo',
    name: 'ZoomInfo',
    domain: 'zoominfo.com',
    stage: 2,
    cat: 'Lead data',
    tagline: 'Enterprise B2B intelligence, company hierarchy, and verified contact database',
    description: 'ZoomInfo maintains extensive business contact coverage, organizational org charts, technographic data, and enterprise intent signals.',
    price: 'Custom quote',
    price_note: 'Custom quote (annual contracts typically starting at $15,000+, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack'],
    feat: false,
    best: 'Enterprise revenue organizations requiring deep US org charts and verified executive direct dials',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Enterprise org chart mapping and executive direct dial verification',
    secondary_capabilities: ['Technographics', 'Web visitor intent (WebSights)', 'Sales workflows'],
    buyer_segment: 'Enterprise sales teams ($50M+ ARR)',
    gtm_buckets: ['Outbound', 'Lead Capture'],
    overlapping_tools: ['apollo', 'cognism'],
    min_plan: 'Custom quote ($15k+/yr)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'lusha',
    slug: 'lusha',
    name: 'Lusha',
    domain: 'lusha.com',
    stage: 2,
    cat: 'Lead data',
    tagline: 'Direct mobile phone numbers and verified B2B email finder extension',
    description: 'Lusha helps sales reps instantly find direct dials and contact info on LinkedIn profiles or company domains and sync them into CRM records.',
    price: 'Free plan',
    price_note: 'Free tier (5 credits/mo); Pro from $36/user/mo ($49 monthly, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Zapier'],
    feat: false,
    best: 'SDRs and account executives needing direct phone numbers while browsing LinkedIn',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Browser extension contact and mobile phone enrichment',
    secondary_capabilities: ['CRM export', 'List enrichment'],
    buyer_segment: 'Sales development reps & small teams',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['apollo', 'cognism'],
    min_plan: 'Free tier / Pro ($36/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'cognism',
    slug: 'cognism',
    name: 'Cognism',
    domain: 'cognism.com',
    stage: 2,
    cat: 'Lead data',
    tagline: 'Phone-verified B2B contact data with premium European and EMEA coverage',
    description: 'Cognism delivers GDPR-compliant B2B contact data with phone-verified Diamond Data numbers, international mobile coverage, and intent signals.',
    price: 'Custom quote',
    price_note: 'Custom quote (annual contracts typically $10,000-$20,000+, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Zapier'],
    feat: false,
    best: 'Outbound sales teams targeting European and international accounts where GDPR compliance is vital',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'GDPR-compliant international mobile number verification',
    secondary_capabilities: ['Bombora intent data integration', 'Chrome extension'],
    buyer_segment: 'Mid-market & Enterprise sales teams targeting EMEA/Global',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['zoominfo', 'apollo'],
    min_plan: 'Custom quote ($10k+/yr)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'seamless-ai',
    slug: 'seamless-ai',
    name: 'Seamless.AI',
    domain: 'seamless.ai',
    stage: 2,
    cat: 'Lead data',
    tagline: 'Real-time search engine for B2B buyer emails and cell phone numbers',
    description: 'Seamless.AI searches open web data in real-time to find contact information for prospective buyers across major industries.',
    price: 'Free plan',
    price_note: 'Free tier (50 credits); Pro tier custom quote / annual contract (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Zapier'],
    feat: false,
    best: 'Sales reps seeking real-time contact lookups across niche industries',
    setup: 1,
    classification: 'review',
    lifecycle_status: 'active',
    primary_jtbd: 'Real-time B2B contact web search and verification',
    secondary_capabilities: ['Chrome extension', 'Pitch intelligence'],
    buyer_segment: 'SMB sales reps (Review recommended due to user-reported bounce variability)',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['apollo', 'lusha'],
    min_plan: 'Free tier / Pro (Custom quote)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: '6sense',
    slug: '6sense',
    name: '6sense',
    domain: '6sense.com',
    stage: 2,
    cat: 'Intent signals',
    tagline: 'Account-based orchestration platform with predictive AI buying signals',
    description: '6sense analyzes anonymous web research and Dark Funnel behavior to identify accounts in-market, predict buying stages, and trigger orchestrated campaigns.',
    price: 'Custom quote',
    price_note: 'Custom quote (enterprise contracts starting at $25,000-$50,000+/yr, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack'],
    feat: false,
    best: 'Enterprise ABM and marketing teams coordinating complex multi-stakeholder buyer journeys',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Predictive account-level intent discovery and multi-channel ABM orchestration',
    secondary_capabilities: ['Account scoring', 'Digital ad placement', 'Sales alert dashboards'],
    buyer_segment: 'Mid-market to Enterprise ABM teams',
    gtm_buckets: ['Lead Capture', 'Data & Orchestration'],
    overlapping_tools: ['demandbase', 'bombora'],
    min_plan: 'Custom quote ($25k+/yr)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'demandbase',
    slug: 'demandbase',
    name: 'Demandbase',
    domain: 'demandbase.com',
    stage: 2,
    cat: 'Intent signals',
    tagline: 'Account-based marketing, advertising, and intent data platform',
    description: 'Demandbase unites proprietary intent signals, third-party B2B data, and targeted account advertising into an enterprise go-to-market command center.',
    price: 'Custom quote',
    price_note: 'Custom quote (enterprise contracts, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack'],
    feat: false,
    best: 'Enterprise marketing and sales operations teams running targeted account campaigns',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Enterprise ABM account identification and targeted B2B display ads',
    secondary_capabilities: ['Technographic data', 'Intent signal scoring', 'CRM attribution'],
    buyer_segment: 'Enterprise ABM teams',
    gtm_buckets: ['Lead Capture', 'Data & Orchestration'],
    overlapping_tools: ['6sense'],
    min_plan: 'Custom quote',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'bombora',
    slug: 'bombora',
    name: 'Bombora',
    domain: 'bombora.com',
    stage: 2,
    cat: 'Intent signals',
    tagline: 'B2B Company Surge intent data derived from cooperative publisher networks',
    description: 'Bombora monitors consumption surges on 5,000+ business websites to identify when organizations research specific B2B software categories and topics.',
    price: 'Custom quote',
    price_note: 'Custom quote (enterprise data subscriptions typically $25,000+/yr, checked October 2026)',
    ints: ['HubSpot', 'Salesforce'],
    feat: false,
    best: 'Revenue leaders needing third-party intent data to prioritize target account lists',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Third-party topic consumption surge measurement',
    secondary_capabilities: ['Audience segmenting', 'CRM enrichment feeds'],
    buyer_segment: 'Mid-market & Enterprise GTM operations',
    gtm_buckets: ['Lead Capture', 'Data & Orchestration'],
    overlapping_tools: ['6sense', 'demandbase'],
    min_plan: 'Custom quote ($25k+/yr)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'koala',
    slug: 'koala',
    name: 'Koala',
    domain: 'getkoala.com',
    stage: 2,
    cat: 'Intent signals',
    tagline: 'Discontinued product (Acquired by Cursor in July 2025; sunset Sept 30, 2025)',
    description: 'Koala previously identified website accounts and signaled buying intent. The platform was acquired by Cursor in July 2025 and officially shut down on September 30, 2025.',
    price: 'Custom quote',
    price_note: 'Discontinued / Shutdown (Acquired by Cursor; evaluated October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: false,
    best: 'Archived for reference only. Teams seeking modern visitor deanonymization should evaluate RB2B or Warmly.',
    setup: 1,
    classification: 'discontinued',
    lifecycle_status: 'discontinued',
    primary_jtbd: 'Discontinued: Website account identification and intent routing',
    secondary_capabilities: ['Archived entry'],
    buyer_segment: 'Discontinued (Excluded from active recommendations)',
    gtm_buckets: ['Lead Capture'],
    overlapping_tools: ['rb2b', 'warmly'],
    min_plan: 'Discontinued (No active commercial plans)',
    pricing_verified_at: 'October 2026',
    alternatives_note: 'Koala was acquired by Cursor in July 2025 and fully shut down on September 30, 2025. Modern active alternatives include RB2B (free person-level LinkedIn visitor alerts to Slack), Warmly (autonomous orchestration), and 6sense.',
  },

  // --- STAGE 3: ENGAGE ---
  {
    id: 'lemlist',
    slug: 'lemlist',
    name: 'lemlist',
    domain: 'lemlist.com',
    stage: 3,
    cat: 'Email outreach',
    tagline: 'Multi-channel outbound engagement platform with image personalization and warmup',
    description: 'lemlist pairs personalized cold email sequences with LinkedIn action steps, dynamic image/video personalization, and lemwarm deliverability monitoring.',
    price: 'Paid',
    price_note: 'Standard from $39/seat/mo ($59/seat/mo for multichannel, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Zapier'],
    feat: true,
    best: 'Sales teams and agencies wanting visual personalization and integrated multichannel steps',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Personalized multi-channel outbound sequencing (Email + LinkedIn)',
    secondary_capabilities: ['Dynamic image personalization', 'Automated warmup (lemwarm)', 'Email finder'],
    buyer_segment: 'Sales development reps & outbound agencies',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['instantly', 'smartlead'],
    min_plan: 'Standard ($39/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'instantly',
    slug: 'instantly',
    name: 'Instantly',
    domain: 'instantly.ai',
    stage: 3,
    cat: 'Email outreach',
    tagline: 'Scalable cold email sending with unlimited mailbox connections and warmup',
    description: 'Instantly enables high-volume outbound campaigns with automated sender warmup, multi-inbox rotation, lead database access, and unified inbox management.',
    price: 'Paid',
    price_note: 'Growth plan from $37/mo (5,000 active leads, unlimited warmup, checked October 2026)',
    ints: ['Zapier', 'HubSpot'],
    feat: true,
    best: 'Agencies and growth teams scaling cold email volume across distributed secondary domains',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Multi-inbox cold email sending and deliverability warmup at scale',
    secondary_capabilities: ['B2B lead database', 'Unified master inbox', 'Warmup automation'],
    buyer_segment: 'Growth agencies and modern cold outbound teams',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['smartlead', 'lemlist'],
    min_plan: 'Growth ($37/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'smartlead',
    slug: 'smartlead',
    name: 'Smartlead',
    domain: 'smartlead.ai',
    stage: 3,
    cat: 'Email outreach',
    tagline: 'API-driven cold email infrastructure with multi-inbox rotation and client portals',
    description: 'Smartlead distributes outbound campaigns across unlimited mailboxes, maintains email reputation with warmups, and provides white-label portals for agencies.',
    price: 'Paid',
    price_note: 'Basic plan from $39/mo (2,000 active leads, unlimited mailboxes, checked October 2026)',
    ints: ['HubSpot', 'Zapier', 'Slack'],
    feat: true,
    best: 'Agencies and RevOps engineers requiring robust Webhook/API controls and white-label reporting',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Infrastructure-level cold email delivery and agency client management',
    secondary_capabilities: ['White-label agency sub-accounts', 'Master inbox', 'REST API & webhooks'],
    buyer_segment: 'Outbound agencies & growth engineers',
    gtm_buckets: ['Outbound', 'Data & Orchestration'],
    overlapping_tools: ['instantly', 'lemlist'],
    min_plan: 'Basic ($39/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'heyreach',
    slug: 'heyreach',
    name: 'HeyReach',
    domain: 'heyreach.io',
    stage: 3,
    cat: 'LinkedIn outreach',
    tagline: 'Multi-account LinkedIn outreach with proxy rotation and unified sender inbox',
    description: 'HeyReach connects multiple LinkedIn accounts into synchronized outbound campaigns with smart proxy rotation, centralized inbox management, and CRM activity sync.',
    price: 'Paid',
    price_note: 'Starts at $79/mo (1 sender account) or $199/mo (agency tier, checked October 2026)',
    ints: ['HubSpot', 'Zapier'],
    feat: false,
    best: 'Growth agencies and B2B sales teams running multi-seat LinkedIn prospect sequences',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Multi-account LinkedIn sender rotation and centralized reply inbox',
    secondary_capabilities: ['Dedicated residential proxies', 'Unified LinkedIn inbox', 'HubSpot sync'],
    buyer_segment: 'Agencies & SDR squads using LinkedIn prospecting',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['lemlist'],
    min_plan: 'Starter ($79/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'artisan',
    slug: 'artisan',
    name: 'Artisan',
    domain: 'artisan.co',
    stage: 3,
    cat: 'AI SDR agents',
    tagline: 'AI sales development software featuring digital agent Ava for outbound research',
    description: 'Artisan provides Ava, an AI SDR software assistant that researches prospective accounts, writes personalized emails, and runs multi-step campaigns.',
    price: 'Paid',
    price_note: 'Paid tiers starting from ~$249-$500/mo (checked October 2026)',
    ints: ['Salesforce', 'HubSpot', 'Slack'],
    feat: false,
    best: 'Startups and small sales teams aiming to automate initial outbound research and copy drafting',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Automated prospect research and AI draft outreach generation',
    secondary_capabilities: ['Email sender integration', 'Contact data enrichment'],
    buyer_segment: 'Seed/Series A startups without dedicated full-time SDRs',
    gtm_buckets: ['Outbound', 'Agentic Operations'],
    overlapping_tools: ['11x', 'regie-ai'],
    min_plan: 'Starter (~$249/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: '11x',
    slug: '11x',
    name: '11x',
    domain: '11x.ai',
    stage: 3,
    cat: 'AI SDR agents',
    tagline: 'Autonomous digital workers for inbound qualification and outbound prospecting',
    description: '11x develops digital workers (Alice and Jordan) engineered to manage end-to-end outbound prospecting, phone outreach, and inbound lead qualification.',
    price: 'Custom quote',
    price_note: 'Custom quote (enterprise agreements typically $3,000+/mo, checked October 2026)',
    ints: ['Salesforce', 'HubSpot'],
    feat: false,
    best: 'Enterprise and high-growth revenue organizations scaling SDR coverage without human headcount additions',
    setup: 3,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Enterprise-grade autonomous digital worker deployment for sales',
    secondary_capabilities: ['Automated multichannel outreach', 'Conversation handling'],
    buyer_segment: 'Mid-market & Enterprise sales organizations',
    gtm_buckets: ['Outbound', 'Agentic Operations'],
    overlapping_tools: ['artisan', 'regie-ai'],
    min_plan: 'Custom quote ($3,000+/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'cubeo-ai',
    slug: 'cubeo-ai',
    name: 'Cubeo.ai',
    domain: 'cubeo.ai',
    stage: 3,
    cat: 'AI SDR agents',
    tagline: 'Custom B2B autonomous AI agents and workflow orchestration',
    description: 'Cubeo.ai builds and integrates customized autonomous AI workflows for B2B sales teams, customer data processing, and revenue operations.',
    price: 'Custom quote',
    price_note: 'Custom quote / Enterprise onboarding (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: false,
    best: 'Mid-market businesses seeking tailored AI agents integrated into proprietary internal workflows',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Custom enterprise AI agent architecture and workflow implementation',
    secondary_capabilities: ['CRM synchronization', 'Autonomous lead qualification'],
    buyer_segment: 'Mid-market B2B enterprises',
    gtm_buckets: ['Outbound', 'Agentic Operations', 'Data & Orchestration'],
    overlapping_tools: ['mindstudio'],
    min_plan: 'Custom quote',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'regie-ai',
    slug: 'regie-ai',
    name: 'Regie.ai',
    domain: 'regie.ai',
    stage: 3,
    cat: 'AI SDR agents',
    tagline: 'AI-assisted sales engagement platform for account research and sequence drafting',
    description: 'Regie.ai acts as a force multiplier for sales development teams, automating prospect research and multi-channel sequence drafting while keeping human reps in the loop.',
    price: 'Paid',
    price_note: 'Free tier (250 credits); Pro from $49/mo ($41 annual); Team $150/seat/mo; Enterprise custom quote (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack'],
    feat: false,
    best: 'Mid-market sales development teams wanting AI-assisted prospecting without eliminating human review',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'AI-augmented prospecting, sequence drafting, and personalization for human reps',
    secondary_capabilities: ['Content management', 'Power dialer integration', 'Prospect data enrichment'],
    buyer_segment: 'Sales development teams & mid-market sales managers',
    gtm_buckets: ['Outbound', 'Agentic Operations'],
    overlapping_tools: ['copy-ai', 'artisan'],
    min_plan: 'Free tier / Pro ($49/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'mindstudio',
    slug: 'mindstudio',
    name: 'MindStudio',
    domain: 'mindstudio.ai',
    stage: 3,
    cat: 'AI SDR agents',
    tagline: 'No-code builder to create and deploy bespoke AI agents and enterprise workflows',
    description: 'MindStudio allows teams to build enterprise AI applications and assistants without coding, combining multi-model LLMs with vector memory and external API integrations.',
    price: 'Free plan',
    price_note: 'Free tier (development); Starter from $20/mo; Pro from $60/mo (checked October 2026)',
    ints: ['Slack', 'Zapier'],
    feat: false,
    best: 'Operations leaders and product managers deploying proprietary B2B AI workflows without coding',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'No-code enterprise AI agent and assistant application building',
    secondary_capabilities: ['Multi-model routing', 'Vector memory embeddings', 'API webhooks'],
    buyer_segment: 'Operations & RevOps builders',
    gtm_buckets: ['Agentic Operations', 'Data & Orchestration'],
    overlapping_tools: ['n8n', 'cubeo-ai'],
    min_plan: 'Free tier / Starter ($20/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'lindy',
    slug: 'lindy',
    name: 'Lindy',
    domain: 'lindy.ai',
    stage: 3,
    cat: 'AI SDR agents',
    tagline: 'Autonomous AI employees for prospecting, email triage, and lead follow-up',
    description: 'Lindy creates autonomous digital teammates that manage your inbox, follow up on inbound leads, draft personalized emails, and handle routine CRM tasks.',
    price: 'Free plan',
    price_note: 'Free tier (300 credits); Pro from $49/mo (3,000 credits, checked October 2026)',
    ints: ['Slack', 'Google Workspace', 'HubSpot'],
    feat: false,
    best: 'Busy revenue leaders looking to delegate recurring prospecting and inbox follow-up workflows',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Autonomous AI executive assistant for inbox triage and prospecting follow-ups',
    secondary_capabilities: ['Meeting scheduling', 'CRM lead updates', 'Email drafts'],
    buyer_segment: 'Founders & revenue executives',
    gtm_buckets: ['Agentic Operations', 'Outbound'],
    overlapping_tools: ['artisan'],
    min_plan: 'Free tier / Pro ($49/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'qualified',
    slug: 'qualified',
    name: 'Qualified',
    domain: 'qualified.com',
    stage: 3,
    cat: 'Chat and conversion',
    tagline: 'Conversational sales and pipeline generation platform built for Salesforce',
    description: 'Qualified identifies target accounts on your website and instantly connects high-intent visitors with sales reps via live chat, voice calls, and automated meeting scheduling.',
    price: 'Custom quote',
    price_note: 'Custom quote (enterprise pricing typically starting at $3,000+/mo, checked October 2026)',
    ints: ['Salesforce', 'Slack'],
    feat: false,
    best: 'Enterprise B2B revenue teams using Salesforce seeking real-time inbound conversion',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Real-time target account chat routing and Salesforce meeting booking',
    secondary_capabilities: ['Piper AI SDR chatbot', 'Website visitor deanonymization'],
    buyer_segment: 'Enterprise Salesforce revenue teams',
    gtm_buckets: ['Lead Capture', 'Inbound'],
    overlapping_tools: ['intercom', '1mind'],
    min_plan: 'Custom quote ($3,000+/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'intercom',
    slug: 'intercom',
    name: 'Intercom',
    domain: 'intercom.com',
    stage: 3,
    cat: 'Chat and conversion',
    tagline: 'AI-first customer service and inbound sales engagement platform',
    description: 'Intercom powers website messaging, product tours, and customer support with Fin AI, resolving user queries automatically and routing qualified buyers to sales.',
    price: 'Paid',
    price_note: 'Essential from $39/seat/mo + $0.99 per Fin AI resolution (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: true,
    best: 'SaaS companies needing unified customer support, onboarding tours, and inbound sales chat',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Inbound chat capture, Fin AI resolutions, and customer lifecycle messaging',
    secondary_capabilities: ['Product onboarding tours', 'Help center knowledge base', 'Omnichannel routing'],
    buyer_segment: 'Modern SaaS companies from seed to scale',
    gtm_buckets: ['Lead Capture', 'Inbound'],
    overlapping_tools: ['qualified', 'manychat'],
    min_plan: 'Essential ($39/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'manychat',
    slug: 'manychat',
    name: 'Manychat',
    domain: 'manychat.com',
    stage: 3,
    cat: 'Chat and conversion',
    tagline: 'Automated conversational marketing for Instagram DMs, WhatsApp, and Messenger',
    description: 'Manychat captures leads and automates conversations across social direct messaging channels, converting post comments and story mentions into qualified email leads.',
    price: 'Free plan',
    price_note: 'Free tier (up to 1,000 contacts); Pro from $15/mo (checked October 2026)',
    ints: ['HubSpot', 'Zapier', 'Google Workspace'],
    feat: false,
    best: 'Creators, agencies, and businesses driving lead acquisition via Instagram and WhatsApp campaigns',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Social DM automation (Instagram, WhatsApp, Facebook Messenger)',
    secondary_capabilities: ['Story mention auto-reply', 'Keyword triggers', 'SMS integration'],
    buyer_segment: 'Social-led brands, marketing agencies, and creators',
    gtm_buckets: ['Lead Capture', 'Inbound'],
    overlapping_tools: ['intercom'],
    min_plan: 'Free tier / Pro ($15/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'drift',
    slug: 'drift',
    name: 'Drift',
    domain: 'drift.com',
    stage: 3,
    cat: 'Chat and conversion',
    tagline: 'Sunsetting standalone platform (Transitioning to 1mind following Salesloft merger)',
    description: 'Drift was a pioneer in B2B conversational marketing. In March 2026, Clari + Salesloft announced the gradual sunset of the standalone Drift chatbot product, partnering with 1mind as the designated successor.',
    price: 'Custom quote',
    price_note: 'Sunsetting standalone platform (Evaluated October 2026)',
    ints: ['Salesforce', 'HubSpot'],
    feat: false,
    best: 'Existing contract renewals only. New deployments should evaluate 1mind, Intercom Fin, or Qualified.',
    setup: 3,
    classification: 'sunsetting',
    lifecycle_status: 'sunsetting',
    primary_jtbd: 'Sunsetting: Conversational chatbot marketing and calendar booking',
    secondary_capabilities: ['Legacy account maintenance'],
    buyer_segment: 'Legacy enterprise customers in contract transition',
    gtm_buckets: ['Lead Capture'],
    overlapping_tools: ['1mind', 'qualified', 'intercom'],
    min_plan: 'Sunsetting (No new standalone sales)',
    pricing_verified_at: 'October 2026',
    alternatives_note: 'Clari + Salesloft announced the gradual sunset of standalone Drift in March 2026, partnering with 1mind as the designated successor. For new purchases, evaluate 1mind, Qualified, or Intercom Fin.',
  },

  // --- STAGE 4: CLOSE ---
  {
    id: 'gong',
    slug: 'gong',
    name: 'Gong',
    domain: 'gong.io',
    stage: 4,
    cat: 'Call intelligence',
    tagline: 'Revenue intelligence and conversation analytics platform',
    description: 'Gong captures and analyzes customer interactions across video calls, phone conversations, and emails to provide deal visibility, coaching metrics, and pipeline forecasts.',
    price: 'Custom quote',
    price_note: 'Custom quote (typically $1,200-$1,600/rep/yr plus base platform fee, checked October 2026)',
    ints: ['Salesforce', 'HubSpot', 'Slack'],
    feat: true,
    best: 'Mid-market and enterprise sales leaders needing rigorous deal risk inspection and rep coaching',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Deal pipeline risk detection, rep call coaching, and revenue intelligence',
    secondary_capabilities: ['Competitor mention tracking', 'Deal board warnings', 'AI call summaries'],
    buyer_segment: 'Mid-market ($20M+ ARR) & Enterprise sales teams',
    gtm_buckets: ['Agentic Operations', 'Data & Orchestration'],
    overlapping_tools: ['chorus', 'fathom', 'tl-dv'],
    min_plan: 'Custom quote ($1,200+/rep/yr)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'chorus',
    slug: 'chorus',
    name: 'Chorus',
    domain: 'chorus.ai',
    stage: 4,
    cat: 'Call intelligence',
    tagline: 'Conversation intelligence and sales call coaching integrated into ZoomInfo',
    description: 'Chorus by ZoomInfo records and transcribes sales calls, pinpointing moments of buyer hesitation, competitor mentions, and pricing discussions.',
    price: 'Custom quote',
    price_note: 'Custom quote via ZoomInfo enterprise licensing (checked October 2026)',
    ints: ['Salesforce', 'HubSpot', 'Slack'],
    feat: false,
    best: 'Sales teams heavily integrated into the ZoomInfo enterprise software ecosystem',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Sales call recording, coaching snippets, and ZoomInfo pipeline sync',
    secondary_capabilities: ['Deal risk alerts', 'Topic trackers'],
    buyer_segment: 'Enterprise sales teams using ZoomInfo',
    gtm_buckets: ['Agentic Operations'],
    overlapping_tools: ['gong', 'fathom'],
    min_plan: 'Custom quote (via ZoomInfo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'calilio',
    slug: 'calilio',
    name: 'Calilio',
    domain: 'calilio.com',
    stage: 4,
    cat: 'Call intelligence',
    tagline: 'Cloud business phone system with VoIP and AI conversation analytics',
    description: 'Calilio provides international business phone numbers, virtual PBX calling, automated SMS, and AI-powered call transcription for distributed teams.',
    price: 'Paid',
    price_note: 'Basic from $12/user/mo; Business from $24/user/mo (checked October 2026)',
    ints: ['Slack', 'Zapier'],
    feat: false,
    best: 'Small businesses and distributed support teams requiring international virtual numbers',
    setup: 2,
    classification: 'review',
    lifecycle_status: 'active',
    primary_jtbd: 'Cloud VoIP telephony and basic call transcription',
    secondary_capabilities: ['Virtual numbers', 'SMS routing'],
    buyer_segment: 'SMB sales & customer support teams',
    gtm_buckets: ['Agentic Operations'],
    overlapping_tools: [],
    min_plan: 'Basic ($12/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'fathom',
    slug: 'fathom',
    name: 'Fathom',
    domain: 'fathom.video',
    stage: 4,
    cat: 'Meeting notes',
    tagline: 'Free AI meeting recorder and CRM note-taker for Zoom, Meet, and Teams',
    description: 'Fathom joins your video meetings, transcribes conversations in real-time, generates structured summary highlights, and automatically synchronizes notes directly into CRM deals.',
    price: 'Free plan',
    price_note: 'Free plan (unlimited individual recordings); Team Edition from $24/seat/mo (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Google Workspace'],
    feat: true,
    best: 'Account executives and founders wanting instant CRM call note synchronization without subscription overhead',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'AI meeting transcription, action item extraction, and native CRM deal logging',
    secondary_capabilities: ['Deal question templates', 'Call sharing', 'Zapier triggers'],
    buyer_segment: 'Sales reps, founders, and revenue teams of all sizes',
    gtm_buckets: ['Agentic Operations', 'Data & Orchestration'],
    overlapping_tools: ['tl-dv', 'meetgeek', 'fireflies-ai'],
    min_plan: 'Free tier / Team ($24/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'tl-dv',
    slug: 'tl-dv',
    name: 'tl;dv',
    domain: 'tldv.io',
    stage: 4,
    cat: 'Meeting notes',
    tagline: 'AI meeting recorder and sales coaching assistant for Google Meet and Zoom',
    description: 'tl;dv captures video meetings with speaker recognition, automated timestamps, multi-language transcription, and AI-generated CRM deal takeaways.',
    price: 'Free plan',
    price_note: 'Free tier (unlimited recordings); Pro from $18/seat/mo (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: false,
    best: 'Product, sales, and customer success teams sharing timestamped meeting clips',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Video meeting recording, timestamped clip sharing, and AI summaries',
    secondary_capabilities: ['Multi-language support', 'CRM sync', 'Team video library'],
    buyer_segment: 'Cross-functional revenue & product teams',
    gtm_buckets: ['Agentic Operations'],
    overlapping_tools: ['fathom', 'meetgeek'],
    min_plan: 'Free tier / Pro ($18/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'meetgeek',
    slug: 'meetgeek',
    name: 'MeetGeek',
    domain: 'meetgeek.ai',
    stage: 4,
    cat: 'Meeting notes',
    tagline: 'AI meeting assistant that records, summarizes, and automatically shares highlights',
    description: 'MeetGeek acts as an automated virtual note-taker for video calls, drafting summaries, highlighting customer sentiment, and syncing action items to Slack and Trello.',
    price: 'Free plan',
    price_note: 'Free tier (5 hrs/mo); Pro from $15/seat/mo ($19 monthly, checked October 2026)',
    ints: ['HubSpot', 'Slack', 'Google Workspace', 'Zapier'],
    feat: false,
    best: 'Agencies and consultants managing high call volumes across multiple client accounts',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Automated video call summaries and team meeting knowledge sharing',
    secondary_capabilities: ['Meeting KPIs', 'Slack highlight pushes'],
    buyer_segment: 'Consultancies & distributed agencies',
    gtm_buckets: ['Agentic Operations'],
    overlapping_tools: ['fathom', 'fireflies-ai'],
    min_plan: 'Free tier / Pro ($15/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'fireflies-ai',
    slug: 'fireflies-ai',
    name: 'Fireflies.ai',
    domain: 'fireflies.ai',
    stage: 4,
    cat: 'Meeting notes',
    tagline: 'AI voice assistant that transcribes, searches, and analyzes voice conversations',
    description: 'Fireflies.ai plugs into Google Meet, Zoom, and Teams to transcribe conversations, track talk-to-listen ratios, and log call summaries into leading CRMs.',
    price: 'Free plan',
    price_note: 'Free tier (limited credits); Pro from $10/user/mo ($18 monthly, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: false,
    best: 'Teams seeking automated searchable audio archives across all internal and external calls',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Searchable call audio transcription and sentiment tracking',
    secondary_capabilities: ['Speaker metrics', 'Automated CRM deal logging'],
    buyer_segment: 'Sales & customer success departments',
    gtm_buckets: ['Agentic Operations'],
    overlapping_tools: ['fathom', 'tl-dv'],
    min_plan: 'Free tier / Pro ($10/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'hubspot-sales-hub',
    slug: 'hubspot-sales-hub',
    name: 'HubSpot Sales Hub',
    domain: 'hubspot.com',
    stage: 4,
    cat: 'CRM',
    tagline: 'All-in-one sales CRM platform with deal management and pipeline tracking',
    description: 'HubSpot Sales Hub unifies contact records, deal stages, email tracking, quoting, and conversation intelligence into an ecosystem loved by scaling teams.',
    price: 'Free plan',
    price_note: 'Free CRM tier; Starter from $15/seat/mo; Professional from $90-$100/seat/mo (checked October 2026)',
    ints: ['Salesforce', 'Slack', 'Zapier', 'Google Workspace'],
    feat: true,
    best: 'Startups and scaling B2B companies looking for a unified CRM that aligns sales with marketing',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Full-lifecycle CRM deal tracking and sales pipeline management',
    secondary_capabilities: ['Email tracking', 'Document quoting', 'Meeting links', 'Workflows'],
    buyer_segment: 'Startups to Mid-market ($1M to $50M ARR)',
    gtm_buckets: ['Data & Orchestration', 'Inbound', 'Outbound'],
    overlapping_tools: ['salesforce-sales-cloud', 'attio', 'pipedrive'],
    min_plan: 'Free tier / Starter ($15/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'salesforce-sales-cloud',
    slug: 'salesforce-sales-cloud',
    name: 'Salesforce Sales Cloud',
    domain: 'salesforce.com',
    stage: 4,
    cat: 'CRM',
    tagline: 'The global enterprise standard CRM platform with customizable revenue data models',
    description: 'Salesforce Sales Cloud offers comprehensive lead and opportunity tracking, enterprise forecasting, workflow rules, and thousands of AppExchange ecosystem integrations.',
    price: 'Paid',
    price_note: 'Starter Suite from $25/user/mo; Pro Suite $100/user/mo; Enterprise $165/user/mo (checked October 2026)',
    ints: ['Slack', 'Zapier', 'Google Workspace'],
    feat: true,
    best: 'Enterprise and complex sales organizations requiring custom relational data models and governance',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Enterprise relational CRM, pipeline governance, and revenue forecasting',
    secondary_capabilities: ['AppExchange ecosystem', 'Einstein AI co-pilot', 'Territory planning'],
    buyer_segment: 'Mid-market & Enterprise ($50M+ ARR)',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['hubspot-sales-hub'],
    min_plan: 'Starter Suite ($25/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'attio',
    slug: 'attio',
    name: 'Attio',
    domain: 'attio.com',
    stage: 4,
    cat: 'CRM',
    tagline: 'Real-time, data-driven CRM built with custom objects and automated email sync',
    description: 'Attio combines the flexibility of a modern database with an intuitive CRM interface, automatically synchronizing company communication history and relationship records.',
    price: 'Free plan',
    price_note: 'Free tier (up to 3 users); Plus from $29/user/mo; Pro from $59/user/mo (checked October 2026)',
    ints: ['Slack', 'Zapier', 'Google Workspace'],
    feat: true,
    best: 'Modern tech companies, VC funds, and founders seeking a clean database-first CRM experience',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Custom object relationship management with automated email/calendar sync',
    secondary_capabilities: ['Automated email sync', 'Visual deal boards', 'API webhooks'],
    buyer_segment: 'Modern startups, venture funds, and product-led teams',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['hubspot-sales-hub', 'folk'],
    min_plan: 'Free tier / Plus ($29/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'folk',
    slug: 'folk',
    name: 'folk',
    domain: 'folk.app',
    stage: 4,
    cat: 'CRM',
    tagline: 'Lightweight collaborative CRM for contacts, pipeline management, and outreach',
    description: 'folk provides an intuitive Notion-like interface to organize contacts, manage deal pipelines, track interactions, and send mail merges with custom variables.',
    price: 'Free plan',
    price_note: 'Free tier (100 contacts); Standard from $18/user/mo ($24 monthly, checked October 2026)',
    ints: ['Google Workspace', 'Zapier'],
    feat: false,
    best: 'Boutique agencies, recruiters, and consultants wanting a quick, flexible contact manager',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Simple contact organization, collaborative pipelines, and light mail merges',
    secondary_capabilities: ['Chrome contact clipper', 'Personalized email sends'],
    buyer_segment: 'Consultants, agencies, and small investment teams',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['attio'],
    min_plan: 'Free tier / Standard ($18/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'pandadoc',
    slug: 'pandadoc',
    name: 'PandaDoc',
    domain: 'pandadoc.com',
    stage: 4,
    cat: 'Document automation',
    tagline: 'Document workflow automation with CPQ quoting and compliant e-signatures',
    description: 'PandaDoc accelerates deal closing with proposal templates, interactive pricing tables, CRM auto-sync, and legally binding e-signatures.',
    price: 'Paid',
    price_note: '14-day trial; Essentials from $19/seat/mo ($35 monthly, checked October 2026)',
    ints: ['Google Workspace', 'HubSpot', 'Salesforce', 'Zapier'],
    feat: false,
    best: 'Sales reps and agency owners looking to cut proposal creation time and close deals faster',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Proposal creation, quote generation, and legally binding e-signatures',
    secondary_capabilities: ['Interactive pricing tables', 'CRM data fields sync', 'Document tracking analytics'],
    buyer_segment: 'Sales teams and agencies sending proposals/contracts',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: [],
    min_plan: 'Essentials ($19/seat/mo)',
    pricing_verified_at: 'October 2026',
  },

  // --- STAGE 5: GROW ---
  {
    id: 'customer-io',
    slug: 'customer-io',
    name: 'Customer.io',
    domain: 'customer.io',
    stage: 5,
    cat: 'Email and lifecycle',
    tagline: 'Automated messaging platform powered by real-time customer behavioral data',
    description: 'Customer.io triggers email, push, and SMS messaging based on app activity, helping product-led B2B SaaS businesses onboard and retain customers.',
    price: 'Paid',
    price_note: 'Essentials from $100/mo (up to 5,000 profiles, checked October 2026)',
    ints: ['Slack', 'Zapier'],
    feat: false,
    best: 'Product-led B2B SaaS companies sending behavioral lifecycle and onboarding sequences',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Behavioral event-triggered customer onboarding and lifecycle messaging',
    secondary_capabilities: ['Multi-channel branching', 'In-app messages', 'Visual journey builder'],
    buyer_segment: 'Product-led B2B SaaS & mobile applications',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['userlist', 'klaviyo'],
    min_plan: 'Essentials ($100/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'klaviyo',
    slug: 'klaviyo',
    name: 'Klaviyo',
    domain: 'klaviyo.com',
    stage: 5,
    cat: 'Email and lifecycle',
    tagline: 'Intelligent marketing automation for email, SMS, and customer retention',
    description: 'Klaviyo unifies consumer customer data to deliver personalized email flows, SMS campaigns, and predictive lifetime value calculations.',
    price: 'Free plan',
    price_note: 'Free tier (up to 250 contacts); Paid tiers start from $20/mo (checked October 2026)',
    ints: ['Zapier'],
    feat: false,
    best: 'E-commerce and consumer-facing B2B brands driving repeat customer revenue',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Automated revenue-driven email and SMS marketing flows',
    secondary_capabilities: ['Predictive customer lifetime value', 'Segment builder'],
    buyer_segment: 'E-commerce and digital consumer brands',
    gtm_buckets: ['Inbound', 'Data & Orchestration'],
    overlapping_tools: ['customer-io'],
    min_plan: 'Free tier / Paid ($20/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'userlist',
    slug: 'userlist',
    name: 'Userlist',
    domain: 'userlist.com',
    stage: 5,
    cat: 'Email and lifecycle',
    tagline: 'Email marketing platform built specifically for B2B SaaS companies',
    description: 'Userlist tracks both individual users and company accounts, making it effortless to send company-level onboarding campaigns and upgrade prompts.',
    price: 'Paid',
    price_note: 'Basic from $149/mo (up to 5,000 company profiles, checked October 2026)',
    ints: ['Zapier'],
    feat: false,
    best: 'B2B SaaS founders wanting clean account-level lifecycle messaging without complex configuration',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'B2B account-level customer lifecycle emails and onboarding journeys',
    secondary_capabilities: ['Company account modeling', 'Broadcast newsletters'],
    buyer_segment: 'B2B SaaS companies',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['customer-io'],
    min_plan: 'Basic ($149/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'vitally',
    slug: 'vitally',
    name: 'Vitally',
    domain: 'vitally.io',
    stage: 5,
    cat: 'Customer success',
    tagline: 'Collaborative customer success platform with real-time account health scoring',
    description: 'Vitally unifies product analytics, customer data, and conversation history to give CS teams customer 360s, automated health scores, and proactive churn mitigation playbooks.',
    price: 'Custom quote',
    price_note: 'Custom quote (tailored onboarding for mid-market CS teams; checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: false,
    best: 'B2B SaaS customer success teams needing automated health scoring and proactive retention workflows',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Account 360 health scoring, customer success task management, and churn mitigation',
    secondary_capabilities: ['Automated CS playbooks', 'Client collaboration portals', 'Product usage sync'],
    buyer_segment: 'Mid-market & High-growth SaaS CS teams',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['churnzero'],
    min_plan: 'Custom quote',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'churnzero',
    slug: 'churnzero',
    name: 'ChurnZero',
    domain: 'churnzero.com',
    stage: 5,
    cat: 'Customer success',
    tagline: 'Enterprise customer success platform for subscription retention and account expansion',
    description: 'ChurnZero helps subscription businesses understand product usage, automate customer onboarding, prevent churn, and identify net retention expansion opportunities.',
    price: 'Custom quote',
    price_note: 'Custom quote (enterprise contracts, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack'],
    feat: false,
    best: 'Enterprise customer success teams managing complex multi-tier recurring revenue accounts',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Enterprise customer health monitoring, churn prevention, and account expansion',
    secondary_capabilities: ['In-app walkthroughs', 'Automated Plays', 'Executive dashboards'],
    buyer_segment: 'Mid-market & Enterprise subscription software companies',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['vitally'],
    min_plan: 'Custom quote',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'clari',
    slug: 'clari',
    name: 'Clari',
    domain: 'clari.com',
    stage: 5,
    cat: 'Revenue forecasting',
    tagline: 'Revenue cadence, pipeline execution, and forecasting platform',
    description: 'Clari gives executive teams complete visibility across the revenue lifecycle, forecasting closed revenue accurately and enforcing pipeline discipline.',
    price: 'Custom quote',
    price_note: 'Custom quote (enterprise minimums typically $1,000+/rep/yr, checked October 2026)',
    ints: ['Salesforce', 'HubSpot', 'Slack'],
    feat: false,
    best: 'Enterprise CROs and sales operations leaders requiring strict quarterly forecasting accuracy',
    setup: 3,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Quarterly sales forecasting, deal slippage detection, and pipeline hygiene',
    secondary_capabilities: ['Revenue leak analytics', 'CRM update automation', 'Executive dashboards'],
    buyer_segment: 'Enterprise sales organizations ($30M+ ARR)',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['boostup', 'gong'],
    min_plan: 'Custom quote ($1,000+/rep/yr)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'boostup',
    slug: 'boostup',
    name: 'BoostUp',
    domain: 'boostup.ai',
    stage: 5,
    cat: 'Revenue forecasting',
    tagline: 'AI revenue intelligence and predictive pipeline forecasting platform',
    description: 'BoostUp monitors deal activity and buyer sentiment to deliver automated forecasting, pipeline inspection, and actionable risk alerts for sales leaders.',
    price: 'Custom quote',
    price_note: 'Custom quote (checked October 2026)',
    ints: ['Salesforce', 'HubSpot', 'Slack'],
    feat: false,
    best: 'Sales operations managers seeking flexible pipeline forecasting models',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Predictive deal inspection and pipeline forecasting',
    secondary_capabilities: ['Activity capture', 'Pipeline review boards'],
    buyer_segment: 'Mid-market sales organizations',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['clari'],
    min_plan: 'Custom quote',
    pricing_verified_at: 'October 2026',
  },

  // --- HIGH-PRIORITY MISSING TOOLS (12 TOOLS ADDED) ---
  {
    id: 'n8n',
    slug: 'n8n',
    name: 'n8n',
    domain: 'n8n.io',
    stage: 4,
    cat: 'Workflow automation',
    tagline: 'Fair-code workflow automation and AI agent orchestration platform',
    description: 'n8n allows technical growth and revops teams to build advanced multi-step automations and AI agent chains with self-hosting control or cloud execution.',
    price: 'Free plan',
    price_note: 'Community Edition is free (self-hosted); Cloud Starter from €20/mo (~$22/mo, checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier', 'Google Workspace'],
    feat: true,
    best: 'Technical RevOps and engineering teams needing flexible, code-capable automations without per-task execution fees',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Self-hostable workflow automation and AI agent orchestration chains',
    secondary_capabilities: ['JavaScript/Python code execution', 'AI agent nodes', 'Custom webhook handling'],
    buyer_segment: 'Technical RevOps, engineers, and growth hackers',
    gtm_buckets: ['Data & Orchestration', 'Agentic Operations'],
    overlapping_tools: ['make', 'zapier'],
    min_plan: 'Community Edition (Free) / Cloud (€20/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'make',
    slug: 'make',
    name: 'Make',
    domain: 'make.com',
    stage: 4,
    cat: 'Workflow automation',
    tagline: 'Visual integration platform for connecting apps and automating revenue workflows',
    description: 'Make provides an intuitive visual canvas to connect apps, route webhook payloads, and automate complex B2B sales operations at scale.',
    price: 'Free plan',
    price_note: 'Free tier (1,000 ops/mo); Core starts at $9/mo; Pro from $16/mo (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier', 'Google Workspace'],
    feat: true,
    best: 'Growth teams and ops managers who want powerful visual branch logic at a fraction of Zapier’s cost',
    setup: 2,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Visual drag-and-drop workflow automation and multi-step data transformation',
    secondary_capabilities: ['Data routers', 'Error-handling routes', 'JSON parsing'],
    buyer_segment: 'Growth teams, RevOps, and digital agencies',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['zapier', 'n8n'],
    min_plan: 'Free tier / Core ($9/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'zapier',
    slug: 'zapier',
    name: 'Zapier',
    domain: 'zapier.com',
    stage: 4,
    cat: 'Workflow automation',
    tagline: 'The standard no-code integration platform with 7,000+ app connectors',
    description: 'Zapier connects sales, marketing, and CRM software with reliable triggers and actions, automated error handling, and built-in AI copilot logic.',
    price: 'Free plan',
    price_note: 'Free tier (100 tasks/mo); Starter from $19.99/mo (annual); Pro from $29.99/mo (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Google Workspace'],
    feat: true,
    best: 'Non-technical operators needing instant out-of-the-box connectors for virtually any business software',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Instant no-code trigger-action app integrations across thousands of SaaS apps',
    secondary_capabilities: ['AI prompt steps', 'Filter logic', 'Tables & Interfaces'],
    buyer_segment: 'Non-technical business operators and small teams',
    gtm_buckets: ['Data & Orchestration'],
    overlapping_tools: ['make', 'n8n'],
    min_plan: 'Free tier / Starter ($19.99/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'pipedrive',
    slug: 'pipedrive',
    name: 'Pipedrive',
    domain: 'pipedrive.com',
    stage: 4,
    cat: 'CRM',
    tagline: 'Activity-based sales CRM designed to keep deals moving through the pipeline',
    description: 'Pipedrive provides visual kanban pipeline management, email tracking, automated activity reminders, and revenue forecasting for sales teams.',
    price: 'Paid',
    price_note: 'Essential from $14/user/mo (annual); Advanced $29/user/mo; Professional $49/user/mo (checked October 2026)',
    ints: ['Google Workspace', 'Slack', 'Zapier', 'HubSpot'],
    feat: true,
    best: 'Sales-led small and midsize teams focused on high deal velocity and simple pipeline hygiene',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Visual deal pipeline tracking and sales activity management',
    secondary_capabilities: ['LeadBooster chatbot', 'Email synchronization', 'Smart contact data'],
    buyer_segment: 'Small to mid-market sales-led teams (1-50 reps)',
    gtm_buckets: ['Outbound', 'Inbound'],
    overlapping_tools: ['hubspot-sales-hub', 'close-crm'],
    min_plan: 'Essential ($14/user/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'close-crm',
    slug: 'close-crm',
    name: 'Close',
    domain: 'close.com',
    stage: 4,
    cat: 'CRM',
    tagline: 'High-velocity CRM with built-in calling, SMS, and multi-channel email sequencing',
    description: 'Close combines deal management with native two-way email, power dialer calling, and SMS automation into a single fast interface designed for inside sales.',
    price: 'Paid',
    price_note: 'Solo $49/mo (1 user); Startup $99/mo (includes 3 users); Professional $299/mo (checked October 2026)',
    ints: ['Google Workspace', 'Slack', 'Zapier'],
    feat: false,
    best: 'Outbound inside sales teams and SDR squads who want communication tools natively bundled into their CRM',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Inside sales deal execution with native calling, SMS, and email sequencing',
    secondary_capabilities: ['Power dialer', 'Two-way SMS sync', 'Multi-channel sequences'],
    buyer_segment: 'Inside sales teams, outbound SDR squads, and startups',
    gtm_buckets: ['Outbound', 'Lead Capture'],
    overlapping_tools: ['pipedrive', 'apollo'],
    min_plan: 'Solo ($49/mo) / Startup ($99/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'hunter',
    slug: 'hunter',
    name: 'Hunter',
    domain: 'hunter.io',
    stage: 2,
    cat: 'Lead data',
    tagline: 'Domain search, email discovery, and verification for outbound outreach',
    description: 'Hunter uncovers verified professional email addresses behind any domain name, verifies deliverability, and includes a simple cold email sender.',
    price: 'Free plan',
    price_note: 'Free tier (25 searches/mo); Starter from $34/mo (annual) or $49/mo monthly (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Zapier', 'Google Workspace'],
    feat: false,
    best: 'Outbound sales reps and marketers needing quick domain lookups and email validation',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Domain email pattern discovery and email address verification',
    secondary_capabilities: ['Chrome extension', 'Cold email campaigns', 'Bulk email verifier'],
    buyer_segment: 'Sales reps, recruiters, and outbound marketers',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['apollo', 'findymail'],
    min_plan: 'Free tier / Starter ($34/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'dropcontact',
    slug: 'dropcontact',
    name: 'Dropcontact',
    domain: 'dropcontact.com',
    stage: 2,
    cat: 'Lead data',
    tagline: '100% GDPR-compliant B2B email enrichment and CRM contact deduplication',
    description: 'Dropcontact cleans, deduplicates, and enriches contact records using proprietary algorithms without storing non-compliant static databases.',
    price: 'Paid',
    price_note: 'Starts at €24/mo (~$26/mo for 1,000 credits); CRM integration plans from €38/mo (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Pipedrive', 'Zapier'],
    feat: false,
    best: 'European and international B2B teams requiring strict GDPR compliance and automated CRM data hygiene',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Automated CRM contact enrichment, deduplication, and GDPR-compliant email search',
    secondary_capabilities: ['Native CRM sync', 'First name capitalization fix', 'Direct dial discovery'],
    buyer_segment: 'European B2B companies & RevOps managers',
    gtm_buckets: ['Outbound', 'Data & Orchestration'],
    overlapping_tools: ['clay', 'apollo'],
    min_plan: '€24/mo (1,000 credits)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'findymail',
    slug: 'findymail',
    name: 'Findymail',
    domain: 'findymail.com',
    stage: 2,
    cat: 'Lead data',
    tagline: 'High-accuracy B2B email finder and automated list scraper with built-in cleaning',
    description: 'Findymail scrapes and finds verified B2B email addresses from LinkedIn Sales Navigator and Apollo, filtering out invalid and risky addresses automatically.',
    price: 'Paid',
    price_note: 'Starts at $49/mo (1,000 verified credits); Pro $99/mo (2,500 credits, checked October 2026)',
    ints: ['Zapier'],
    feat: false,
    best: 'Outbound growth teams seeking ultra-low bounce rate email waterfalls for cold campaigns',
    setup: 1,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'High-accuracy B2B email extraction and verification from LinkedIn and Apollo',
    secondary_capabilities: ['Automated list export', 'Clean contact formatting'],
    buyer_segment: 'Cold outbound specialists & growth agencies',
    gtm_buckets: ['Outbound'],
    overlapping_tools: ['hunter', 'clay'],
    min_plan: '$49/mo (1,000 credits)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'rb2b',
    slug: 'rb2b',
    name: 'RB2B',
    domain: 'rb2b.com',
    stage: 2,
    cat: 'Intent signals',
    tagline: 'Person-level website visitor identification delivering US LinkedIn profiles to Slack',
    description: 'RB2B resolves anonymous US website visitors down to the individual person level and pushes their LinkedIn profile directly to Slack channels for immediate outreach.',
    price: 'Free plan',
    price_note: 'Free tier (100 identified profiles/mo); Pro tier from $99/mo (checked October 2026)',
    ints: ['Slack', 'HubSpot', 'Zapier'],
    feat: true,
    best: 'B2B sales teams wanting high-intent individual visitor identification without enterprise contract minimums (Top Koala alternative)',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Individual person-level US website visitor identification and Slack notifications',
    secondary_capabilities: ['LinkedIn profile resolution', 'Webhook integrations', 'HubSpot sync'],
    buyer_segment: 'B2B startups and outbound sales teams targeting US buyers',
    gtm_buckets: ['Lead Capture', 'Inbound'],
    overlapping_tools: ['warmly', '6sense'],
    min_plan: 'Free tier (100 profiles/mo) / Pro ($99/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'warmly',
    slug: 'warmly',
    name: 'Warmly',
    domain: 'warmly.ai',
    stage: 2,
    cat: 'Intent signals',
    tagline: 'Autonomous website visitor deanonymization, intent tracking, and instant pipeline orchestration',
    description: 'Warmly reveals accounts browsing your site, enriches buying committee contacts, and dynamically triggers video/chat popups or automated SDR outreach.',
    price: 'Free plan',
    price_note: 'Free tier (up to 500 company reveals/mo); Starter from $400/mo; Custom enterprise (checked October 2026)',
    ints: ['HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: false,
    best: 'Growth-stage B2B companies looking to convert website traffic into outbound pipeline before visitors bounce',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Autonomous website visitor deanonymization and instant live meeting orchestration',
    secondary_capabilities: ['Automated email follow-up', 'Live video chat widgets', 'Buying committee enrichment'],
    buyer_segment: 'B2B growth teams & mid-market sales',
    gtm_buckets: ['Lead Capture', 'Inbound', 'Agentic Operations'],
    overlapping_tools: ['rb2b', 'qualified'],
    min_plan: 'Free tier / Starter ($400/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: 'calendly',
    slug: 'calendly',
    name: 'Calendly',
    domain: 'calendly.com',
    stage: 4,
    cat: 'Meeting notes',
    tagline: 'Automated scheduling, meeting routing forms, and calendar qualification',
    description: 'Calendly removes back-and-forth scheduling friction with automated calendar sync, intake qualifying forms, team round-robin routing, and CRM logging.',
    price: 'Free plan',
    price_note: 'Free tier (1 event type); Standard from $10/seat/mo; Teams from $16/seat/mo (checked October 2026)',
    ints: ['Google Workspace', 'HubSpot', 'Salesforce', 'Slack', 'Zapier'],
    feat: true,
    best: 'Sales teams and consultants needing friction-free meeting bookings and automated routing',
    setup: 1,
    classification: 'core',
    lifecycle_status: 'active',
    primary_jtbd: 'Frictionless meeting scheduling, round-robin lead routing, and qualification forms',
    secondary_capabilities: ['Routing forms', 'Automated reminder workflows', 'CRM calendar sync'],
    buyer_segment: 'Sales reps, agencies, and businesses of all sizes',
    gtm_buckets: ['Inbound', 'Lead Capture'],
    overlapping_tools: [],
    min_plan: 'Free tier / Standard ($10/seat/mo)',
    pricing_verified_at: 'October 2026',
  },
  {
    id: '1mind',
    slug: '1mind',
    name: '1mind',
    domain: '1mind.com',
    stage: 3,
    cat: 'Chat and conversion',
    tagline: 'Autonomous AI buyer engagement platform and interactive product demonstrations',
    description: '1mind deploys autonomous digital teammates that guide inbound prospects through real-time conversations, interactive product demos, and pipeline qualification (official Drift successor).',
    price: 'Custom quote',
    price_note: 'Custom quote (Pilot & enterprise tiers; evaluated October 2026)',
    ints: ['Salesforce', 'HubSpot', 'Slack'],
    feat: false,
    best: 'B2B revenue organizations transitioning from legacy chatbots (like Drift) to autonomous AI inbound conversations',
    setup: 2,
    classification: 'specialist',
    lifecycle_status: 'active',
    primary_jtbd: 'Autonomous inbound AI buyer conversations and interactive product walkthroughs',
    secondary_capabilities: ['Real-time objection handling', 'Automated meeting qualification', 'CRM deal creation'],
    buyer_segment: 'Mid-market & Enterprise sales teams transitioning from legacy chatbots',
    gtm_buckets: ['Inbound', 'Lead Capture', 'Agentic Operations'],
    overlapping_tools: ['qualified', 'intercom'],
    min_plan: 'Custom quote',
    pricing_verified_at: 'October 2026',
  },
];

// Write updated catalog to data/tools.json
const outputPath = path.resolve('./data/tools.json');
fs.writeFileSync(outputPath, JSON.stringify(AUDITED_TOOLS, null, 2), 'utf8');

console.log(`Successfully written ${AUDITED_TOOLS.length} audited tools to ${outputPath}`);
